macos-titlebar-style = tabs
theme = dracula+
font-family = "Iosevka Fixed"
font-size = 15
keybind = shift+enter=text:\x1b\r
shell-integration-features = ssh-env # auto configure SSH to fall back to xterm-256color
